/// <reference types="react" />
import { FC, SVGAttributes } from "react"
export interface IconProps extends SVGAttributes<SVGElement> {
  className?: string
  color?: string
  size?: number
}
export type Icon = FC<IconProps>
export const Add: Icon
export const Apartment: Icon
export const Apartment: Icon
export const Archive: Icon
export const Bath: Icon
export const Bed: Icon
export const BestPrice: Icon
export const BestPrice: Icon
export const Bold: Icon
export const Calendar: Icon
export const Call: Icon
export const Chart: Icon
export const Check: Icon
export const CheckCircle: Icon
export const Check: Icon
export const ChevronDown: Icon
export const ChevronLeft: Icon
export const ChevronRight: Icon
export const ChevronUp: Icon
export const Close: Icon
export const Condominium: Icon
export const Credit: Icon
export const Dashboard: Icon
export const Dashboard: Icon
export const Debt: Icon
export const Document: Icon
export const Document: Icon
export const DocumentRequest: Icon
export const DocumentTwotone: Icon
export const DollarSquare: Icon
export const DollarSquare: Icon
export const Dorm: Icon
export const DotHorizontal: Icon
export const DotVertical: Icon
export const DoubleChecks: Icon
export const DoubleChevronLeft: Icon
export const DoubleChevronRight: Icon
export const Edit: Icon
export const Electricity: Icon
export const Employment: Icon
export const Eye: Icon
export const Eye: Icon
export const EyeSlash: Icon
export const EyeSlash: Icon
export const Filter: Icon
export const GasStation: Icon
export const Help: Icon
export const House: Icon
export const House: Icon
export const Image: Icon
export const IncomeToRent: Icon
export const IncomeToRent: Icon
export const InfoBulk: Icon
export const Info: Icon
export const Insight: Icon
export const Insight: Icon
export const Italic: Icon
export const Key: Icon
export const Key: Icon
export const Link: Icon
export const LocationControl: Icon
export const LocationControl: Icon
export const LocationMarker: Icon
export const LocationMarker: Icon
export const Logout: Icon
export const Love: Icon
export const Love: Icon
export const LowCommision: Icon
export const LowCommision: Icon
export const Map: Icon
export const Medal: Icon
export const Message: Icon
export const Message: Icon
export const Money: Icon
export const MoneyTick: Icon
export const MoneyTick: Icon
export const NewNotification: Icon
export const NewNotification: Icon
export const Notification: Icon
export const Notification: Icon
export const OnTime: Icon
export const OrderedList: Icon
export const Paperclip: Icon
export const Properties: Icon
export const Properties: Icon
export const PropertyInsurance: Icon
export const PropertyInsurance: Icon
export const RecentActivity: Icon
export const RentPayment: Icon
export const RentPayment: Icon
export const Repair: Icon
export const Search: Icon
export const Send: Icon
export const Setting: Icon
export const Setting: Icon
export const Share: Icon
export const Share: Icon
export const SortAscending: Icon
export const SortDescending: Icon
export const Sort: Icon
export const SquareMeters: Icon
export const Star: Icon
export const TenantApplication: Icon
export const Tenants: Icon
export const Tenants: Icon
export const Tips: Icon
export const TourInPerson: Icon
export const TourVirtual: Icon
export const Townhouse: Icon
export const Trash: Icon
export const UnorderedList: Icon
export const User: Icon
export const User: Icon
export const VideoVirtual: Icon
export const Wifi: Icon
